apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-host-path
  labels:
    app: nginx-host-path
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-host-path
  template:
    metadata:
      labels:
        app: nginx-host-path
    spec:
      volumes:
        # Path from the node
        - name: host-path-storage
          hostPath:
            path: /mnt/hostPath
            type: DirectoryOrCreate
      containers:
      - name: nginx-container
        image: nginx
        ports:
          - containerPort: 80
            name: "http-server"
        volumeMounts:
          # Path in the container
          - mountPath: "/usr/share/nginx/html"
            name: host-path-storage
